var browserify = require("browserify")
var to5        = require("6to5-browserify")
var path       = require('path')
var fs         = require('fs')
var targetPath = path.join("..", "src", "breakout.js")
var bundlePath = path.join("public", "breakout.js")

browserify({debug: true})
  .transform(to5)
  .external("dat-gui")
  .require(require.resolve(targetPath), { entry: true })
  .bundle()
  .on('error', function (err) { console.error(err); })
  .pipe(fs.createWriteStream(bundlePath))
